; NSIS Installer Script
; Generated by ExeForge HTML to Windows EXE Builder

!define PRODUCT_NAME "Inventario "
!define PRODUCT_VERSION "1.0.0"
!define PRODUCT_PUBLISHER "Mi Aplicación "
!define PRODUCT_DIR_REGKEY "Software\Microsoft\Windows\CurrentVersion\App Paths\Inventario .exe"
!define PRODUCT_UNINST_KEY "Software\Microsoft\Windows\CurrentVersion\Uninstall\Inventario "

SetCompressor lzma

!include "MUI2.nsh"

Name "Inventario  ${PRODUCT_VERSION}"
OutFile "dist\Inventario -Setup-${PRODUCT_VERSION}.exe"
InstallDir "$PROGRAMFILES\Inventario "
InstallDirRegKey HKLM "${PRODUCT_DIR_REGKEY}" ""
ShowInstDetails show
ShowUnInstDetails show

!insertmacro MUI_PAGE_WELCOME
!insertmacro MUI_PAGE_DIRECTORY
!insertmacro MUI_PAGE_INSTFILES
!insertmacro MUI_PAGE_FINISH

!insertmacro MUI_UNPAGE_INSTFILES

!insertmacro MUI_LANGUAGE "English"

Section "MainSection" SEC01
  SetOutPath "$INSTDIR"
  SetOverwrite ifnewer
  File /r "dist\win-unpacked\*"
  CreateDirectory "$SMPROGRAMS\Inventario "
  CreateShortCut "$SMPROGRAMS\Inventario \Inventario .lnk" "$INSTDIR\Inventario .exe"
  CreateShortCut "$DESKTOP\Inventario .lnk" "$INSTDIR\Inventario .exe"
SectionEnd

Section -Post
  WriteUninstaller "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_DIR_REGKEY}" "" "$INSTDIR\Inventario .exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayName" "Inventario "
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "UninstallString" "$INSTDIR\Uninstall.exe"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "DisplayVersion" "${PRODUCT_VERSION}"
  WriteRegStr HKLM "${PRODUCT_UNINST_KEY}" "Publisher" "Mi Aplicación "
SectionEnd

Section Uninstall
  RMDir /r "$INSTDIR"
  Delete "$SMPROGRAMS\Inventario \Inventario .lnk"
  RMDir "$SMPROGRAMS\Inventario "
  Delete "$DESKTOP\Inventario .lnk"
  DeleteRegKey HKLM "${PRODUCT_UNINST_KEY}"
  DeleteRegKey HKLM "${PRODUCT_DIR_REGKEY}"
SectionEnd
