name: Generar EXE de Windows

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar dependencias
        run: npm install

      - name: Generar EXE
        run: npm run dist

      - name: Guardar EXE
        uses: actions/upload-artifact@v4
        with:
          name: Control-de-Materiales-Windows
          path: dist/*.exe
          if-no-files-found: error
